const decksConst = {
  CREATE_DECK: "DECKCONST:CREATE_DECK",
  CREATE_CARD: "DECKCONST:CREATE_CARD",
  START_QUIZ: "DECKCONST:START_QUIZ",
  IS_CORRECT_QUIZ: "DECKCONST:IS_CORRECT_QUIZ",
  QUIZ_RESET: "DECKCONST:QUIZ_RESET",
};

export default decksConst;